### ISSUE TITLE
glsl-js use-case

### ISSUE THREAD

**Issue by dfcreative** [mikolalysenko/regl#1]
Hi @mikolalysenko!
Nice project.
Please have a look at [glsl → js compiler](https://github.com/dfcreative/glsl-js), it is a bit opinionated, but it may be useful for this project.
It is WIP, so if you have any comments, suggestions or dislikes please let me know.

**Comment by mikolalysenko** [comment]
I think glsl-js is really cool!  However, I don't know that it is necessarily useful for regl, so I'm going to close this issue for now.
