### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#10]
When optimizing WebGL applications it is useful to keep track of how many resources are occupied.  We can do this right now with regl and it expose it to the user transparently.  Some possible stats that we could track:

* Total number of resources (buffers, elements, textures, etc.) which are allocated
* Total GPU memory allocated to each resource type
* Last frame time, maybe average frametime or some histogram of times
* Per-command stats, like execution time, number of vertices drawn, number of texture units, number of attributes used, number of uniforms, etc.

We should also have some infrastructure to take advantage of the [disjoint timer query](https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query/) extension within a draw command and use this to report stats.

**Comment by Erkaman** [comment]
I will take a look at it, and try to make the beginnings of `regl.stats`

**Comment by Erkaman** [comment]
Writing down some additional items:

* We need coarse draw command profiling in case disjoint timer queries are unavailable. Using something like `performance.now()`.
* We need a way of disabling profiling for draw commands. A flag passed to the constructor of the draw command should be good enough
* Some graphical widgets for visualising the draw command time would be nice. Like they do in [stats.js](https://github.com/mrdoob/stats.js/)

**Comment by Erkaman** [comment]
Next, I will make sure that `stats` keep track of this info:

* The total amount of memory used by buffers and textures.
* Shader info: number uniforms, number attributes, and so on
* Maximum number of used texture units.

**Comment by Erkaman** [comment]
Most of the stuff above was implemented in PR #102

**Comment by mikolalysenko** [comment]
Maybe we should close this then.  The info we have now is already pretty good.  If more stuff is needed then we can open a separate issue as it comes up.
