### ISSUE TITLE
`gl.deleteBuffer()` is never called for buffers created through `buffer.createStream() `

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#100]
For buffers created through  `buffer.createStream()`, `gl.deleteBuffer()` is never called, so they are never cleaned up when the program exists. But they should be.

This can probably be easily fixed by adding all stream-buffers to `bufferSet `.

**Comment by mikolalysenko** [comment]
Fixed in #110

**Comment by mikolalysenko** [comment]
Oops, this is a separate issue.  Going to make a fix right now.
