### ISSUE TITLE
More test cases!

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#11]
This is an ongoing process, but the test coverage is still not 100% in regl.  Some parts are pretty good (like basic rendering and buffer uploads), but other parts need more work.  In no particular order, we need to vet the following subsystems:

* Textures (specifically the constructor and multitexturing with many uniforms)
* Instanced rendering
* Rendering across different extension configurations
* Compressed textures
* Constant vertex attributes
* Frame buffer objects

To help discover new things to test there is a code coverage reporting system set up.  To access it, use the command:

```
npm run cover
```

And then open up the results in `coverage/lcov-report/index.html`.

All of the test cases are written using [tape](https://www.npmjs.com/package/tape).  For more info on how to write test cases, check out the [development guide](https://github.com/mikolalysenko/regl/blob/gh-pages/DEVELOPING.md).

**Comment by mikolalysenko** [comment]
This issue is pretty vague.  We should probably split up into more concrete subgoals that are actually tractable.

**Comment by Erkaman** [comment]
Yeah, some subgoals are:

* more cubemap test cases
* compressed texture cases.

**Comment by mikolalysenko** [comment]
Constant vertex attributes are now tested as of #155

**Comment by mikolalysenko** [comment]
I'm going to close this and split out the unfinished tasks into separate issues.

**Comment by Erkaman** [comment]
Good idea.

**Comment by Erkaman** [comment]
This issue got split into the issues #169 and #170
