### ISSUE TITLE
The gallery should be redesigned.

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#126]
Right now, the gallery is freaking fugly:

<img width="285" alt="screen shot 2016-07-25 at 18 14 50" src="https://cloud.githubusercontent.com/assets/602313/17108431/c0246100-5293-11e6-8cd0-ac0ca358fb15.png">

The gallery needs a better design(simply choosing better font and formatting will do wonders), and every entry should have an accompanying image, or even better, a video(I have already recorded a couple already, like [here](https://www.youtube.com/watch?v=OJkT24MxydA) and [here](https://www.youtube.com/watch?v=scg33DHDnHc)). A video or an image is important, since due to extension loading issues, the user may be unable to view the example. For those cases, providing an image or a video is much better than nothing.

**Comment by mikolalysenko** [comment]
We already have some examples on regl.party courtesy of @freeman-lab .  Though having a separate gallery would be great.

Regarding videos, it would be neat if we could have the build script/CI automatically generate and upload them to youtube.

**Comment by Erkaman** [comment]
Yeah, if we can just fix headless so that the most useful extensions work, we will be able to do that with my tool [regl-recorder](https://github.com/Erkaman/regl-recorder)!

**Comment by Erkaman** [comment]
Solved with PR #173.
