### ISSUE TITLE
Benchmark suite and dash board

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#13]
There is a fairly rudimentary benchmark suite for regl, but it doesn't measure much yet.  What exists now is right here:

https://github.com/mikolalysenko/regl/tree/gh-pages/bench

It would be extremely awesome to get this system working more reliably so that we could measure how much overhead each regl command has.  Writing good benchmarks in JavaScript is really hard, especially for a complex system like regl.  To get a good handle on this we probably need to create some more complicated examples with regl and then plug them into the benchmark harness to record statistics information.

Long term, it would also be cool to have this plug into some big dashboard and to track stats over time so we could make sure that things keep improving performance-wise instead of hitting regressions.

**Comment by mikolalysenko** [comment]
Having benchmarks is important to spot performance bugs and also to ensure that future updates don't cause regressions.  The tough part though is figuring out what to measure.  Progress in stats should help here.

**Comment by Erkaman** [comment]
I shall make a benchmarking program that compares regl and webgl. 

First I will write a simple benchmark program in regl(drawing some triangles and stuff), and then I will write another program that does that same thing, but in raw, pure WebGL. And then I will measure and compare their rendering times. Then we can for sure see how much overhead regl will add.

**Comment by Erkaman** [comment]
A dashboard has now been implemented, as part of PR #73.

**Comment by mikolalysenko** [comment]
We should probably break out each of the bench mark tasks into separate actionable issues.  This issue is too vague to do much with it right now.  With the dashboard we can probably close it.

**Comment by gaitat** [comment]
I am assuming that your benchmark tests collect the time before rendering (or setup) starts and after rendering finishes. So in order to benchmark webgl drawing you need to be able to tell when the drawing has finished. I am just wondering how do you achieve that?
