### ISSUE TITLE
regl.read() returns uint8 array instead of the fbo/texture type of float

### ISSUE THREAD

**Issue by realazthat** [mikolalysenko/regl#136]
See the console output, it should be an array of floats in range [0,1], specifically an array of all 1s, instead it is an array of all 255 uints.

```


const image_data = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAACXBIWXMAAABIAAAASABGyWs+AAAA1UlEQVRIx91W0RLDIAgj3P7/l9mDO6ooVifcbuURNWlSTwIRobsCMOyvnH2t4Ho41QaXCcO1cnLh+3S/S8Pn6Lp56KRVAGALupdiALldPkIvUoyOi+AcfcjBih6A3ZphFfh3kYbsXt9A8dwchTBYXr83iim58gmiLk9fxaVfW6TijEqv39f2s7NVwBNu0f8TiEj0Q/epMhseYBERZbiks7OeaJHojQJai1A0HTKmFLCeaDFGmWDR/ORzjj622OgoIl8EL/LDXXp0xCy33offS7cLkh3f34rheTjlbIAQAAAARHpUWHRDb21tZW50AAB42nNNySxJTVFIqlQISCzNUQjOSC3KTcxTSMsvUggPcM7JLEgsKtFRCChNyslMVnDJz03MzAMA0cYSC/gtqgsAAAAASUVORK5CYII=`;
const resl = require('resl');
const regl = require('regl')({
  extensions: ['OES_texture_float', 'OES_texture_float_linear']
});

const quadVerts = [
  [-1.0, -1.0, 0.0], [-1.0, 1.0, 0.0], [1.0, -1.0, 0.0], [1.0, 1.0, 0.0]
];

const quadIndices = [
  [3, 1, 0], [0, 2, 3]
];


resl({
  manifest: {
    texture: {
      type: 'image',
      src: image_data,
      parser: (data) => regl.texture({
        data: data,
        mag: 'nearest',
        min: 'nearest'
      })
    }
  },
  onDone: ({}) => {
    let fbo = regl.framebuffer({
                color: regl.texture({
                  width: 32,
                  height: 32,
                  stencil: false,
                  format: 'rgba',
                  type: 'float',
                  depth: false,
                  wrap: 'clamp'
                })
              });

    const renderToFBO = regl({
      frag: `
        precision mediump float;
        varying vec2 vUv;
        void main () {
          gl_FragColor = vec4(1,1,1,1);
        }
      `,
      vert: `
        precision mediump float;
        attribute vec3 position;
        varying vec2 vUv;
        
        void main() {
          vUv = (position.xy + 1.0)/2.0;
          gl_Position = vec4(position, 1);
        }
      `,
      attributes: {
        position: quadVerts
      },
      elements: quadIndices,
      uniforms: {
      },
      framebuffer: regl.prop('fbo')
    });

    renderToFBO({fbo: fbo});

    var bindFBO = regl({framebuffer: fbo});   bindFBO(() => {
      console.log(regl.read());
    });


  }
});
```

**Comment by Erkaman** [comment]
Yeah, because that feature isn't yet supported by the framework yet. But we forgot to mention that in the docs. Sorry about that.

We discussed this feature in issue #97, but we decided on postponing it for the time being, since it is not possible to portably implement `regl.read()` for floating-point renderbuffers.

But for floating-point FBOs it is possible to do it. We'll just have to put a warning that you can't `regl.read()` from floating point renderbuffers, I guess.

Anyways, I will try adding this feature, and if all goes well, it should be finished in a day or so.

**Comment by Erkaman** [comment]
Alright, the feature has now been implemented, as part of PR #138.
If you now `git pull` the latest version of `regl`, the above program
should work. Please try it out.

**Comment by realazthat** [comment]
@Erkaman It works. The demo code logs a list of 1's. Changing the color in the fragment shader changes the output to the given number including decimal etc.

One thing I wonder, what happens if you have multiple color attachments?

**Comment by Erkaman** [comment]
Hmm, then it would read from the first color attachment, I think?

**Comment by realazthat** [comment]
@Erkaman Just asking the question because it seems like a corner case that might surprise. Thanks for your help :)

**Comment by Erkaman** [comment]
If you want to be able to read from any other color attachment, it is certainly a feature I could add.

But that should be a separate issue. So closed.
