### ISSUE TITLE
Specify color attachments for `gl.read()`

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#139]
If you are using MRT, you can by using [gl.readBuffer(src)](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/readBuffer) specify which color attachment `gl.readPixels.` will read from. So we could use this to  specify which color attachment `regl.read` should read from.

Although it seems to be a WebGL2.0 feature. If we can't use it, we can probably get around it by using `glGetTexImage​` to read from the color attachment texture instead.

This may be a feature we should consider adding.

**Comment by mikolalysenko** [comment]
WebGL doesn't give us a `gl.getTexImage` method, so we can't do it that way, and [WebGL_draw_buffers](https://www.khronos.org/registry/webgl/extensions/WEBGL_draw_buffers/) only exposes the draw buffer.

It isn't clear how to implement this in regl at the moment.

**Comment by Erkaman** [comment]
Oh snap. In that case, it doesn't seem like it is possible to implement...

**Comment by mikolalysenko** [comment]
Ok, closing this then.
