### ISSUE TITLE
`regl.texture` creation difficulty

### ISSUE THREAD

**Issue by rreusser** [mikolalysenko/regl#161]
Goal is to create a floating point texture (even if that's just one component of rgba. it's not optimal, but I'm not that picky at the moment). See: https://github.com/rreusser/regl-smooth-life/blob/master/www/index.js#L62-L67

```javascript
  regl.framebuffer({
    colorBuffer: regl.texture({
      radius: RADIUS,
      data: createInitialConditions(),
      type: 'float',
      wrap: 'repeat',
    }),
  })
```

This worked in regl 0.4.0, but it seems that no matter what I do (including combinations of format and type that, based on the table, seem like they should work), I just get the error message:

```
Error: (regl) unknown parameter (float): invalid texture type. possible values: uint8,rgba4,rgb565,rgb5 a1
```

In a sense, the 'issue' here is likely not code itself (because it's very likely I'm doing something wrong), but the fact that from the error messages and documentation, it's not quite clear why the combinations I've tried don't work. (Specifically, the possible types don't correspond to the specified `format`. Maybe I'm missing something.) I hate to burden you with my usage issues, but any suggestions would be greatly appreciated!

**Comment by rreusser** [comment]
Additional notes:

- looks like `colorBuffer` is no longer a param, but this error seems unrelated to that change
- I followed the advice and tried some of the different texture types, but that didn't get me closer to a combination that had type `float`
- it felt like maybe a length mismatch could conceivably cause this. It felt like maybe the specificity of the error wasn't quite right to indicate the true source of the problem, but that's just guesswork. It could be spot on and the problem is me 😬 
- Once debugged, I'd be glad to submit a PR with an example since this might be a common use case

**Comment by Erkaman** [comment]
`regl` has changed a LOT since 0.0.4, so it is not surprising that this doesn't work anymore.

* You need to explicitly load extensions now. To use a float texture, you must do this when creating regl:

```javascript
var regl = require('regl')({extensions: ['oes_texture_float']});
```

But that error message could be made a lot clearer, though.

* `count` has been renamed to `tick`

* Finally, ` colorBuffer` has been renamed to  `color`.

Try the above, and maybe it works again.

**Comment by Erkaman** [comment]
Also, you should probably spend some timing reading the docs in `API.md` and studying the examples in `example/`, to get a better feel for how the new `regl` should be used. The API is relatively stable at this point.

**Comment by mikolalysenko** [comment]
@rreusser if this solves the issues you were having, then maybe we can close this

**Comment by rreusser** [comment]
Yup. Honestly, I don't know what I did that made this so difficult. I felt like I tried all the permutations I could come up with, but a new day no trouble getting it working. Pardon the usage question! Thanks!
