### ISSUE TITLE
Need examples for stencil buffer

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#163]
Right now, there are no examples that showcases the stencil buffer manipulation features of regl. But we probably need some. One example that we could implement is 

* Shadow Volumes.
* [Planar Reflections](http://www.cse.chalmers.se/edu/year/2015/course/TDA361/shadrefl.pdf#page=60).
* Render object outlines

And anyone who has implemented such an example is very much welcome to submit it, by a pull request!

**Comment by mikolalysenko** [comment]
I have an implementation that I made for webgl-workshop we could adapt:

* https://github.com/stackgl/webgl-workshop/tree/master/exercises/stencil-shadows

**Comment by Erkaman** [comment]
Seems good. Shouldn't be hard to port.

**Comment by Erkaman** [comment]
I shall implement shadow volumes.

**Comment by Erkaman** [comment]
Three demos have been implemented in the issues #184,  #205, and #206. This is enough demos, so closed.
