### ISSUE TITLE
regl.prop() and default values

### ISSUE THREAD

**Issue by realazthat** [mikolalysenko/regl#175]
What is the best way to go about having a default value for regl.prop(...), if the property is not specified when the command is called?

Something like this:

```

const drawToScreen = regl({
  frag: quad.shader.frag,
  vert: quad.shader.vert,
  attributes: {
    a_position: quad.verts,
    a_uv: quad.uvs
  },
  elements: quad.indices,
  uniforms: {
    u_tex: regl.prop('texture'),
    u_clip_y: regl.prop('clip_y', /*default=*/1) // << something like this?
  }
});

```

**Comment by mikolalysenko** [comment]
I like this idea.  Going to leave it to sit here for a bit and if there is no objection I'll go ahead and implement it after a few days.

**Comment by Erkaman** [comment]
I like this idea as well. I have no objections.

**Comment by mikolalysenko** [comment]
Been thinking this through a bit and there are problems.  If you use the same prop in multiple places then you can end up with a confusing situation where you can specify different default values for the same prop.

**Comment by Erkaman** [comment]
Hmm, yeah, that sucks actually. Anyways, I don't really see how this feature is that necessary. You can easily implement default values in our current system like this:

```
var translate = ((typeof props.translate === 'undefined') ? [0.0, 0.0, 0.0] : props.translate)
```

so I don't see the need for this feature.

**Comment by Pyrolistical** [comment]
Its just annoying to have to implement yourself every time.

```js
// note this must be declared by itself and not inlined or else a new instance
// of this command will be created every time.
const reglDrawToScreen = regl({
  frag: quad.shader.frag,
  vert: quad.shader.vert,
  attributes: {
    a_position: quad.verts,
    a_uv: quad.uvs
  },
  elements: quad.indices,
  uniforms: {
    u_tex: regl.prop('texture'),
    u_clip_y: regl.prop('clip_y')
  }
});

const drawToScreen = ({u_clip_y = 1, ...props}) => reglDrawToScreen({u_clip_y, ...props})
```
