### ISSUE TITLE
Explicit attributes should create a buffer for me.

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#179]
When creating explicit attributes, this works:

```javascript
    position: {
      buffer: regl.buffer([1, 2, 3, ...]),
      offset: 0,
      normalized: false,
      stride: 24,
      size: 3
    }
```

but this doesn't work:

```javascript
    position: {
      buffer: [1, 2, 3, ...],
      offset: 0,
      normalized: false,
      stride: 24,
      size: 3
    }
```

but why should I not be able to do the latter? Can't it just infer that it should create a  `regl.buffer` from the array? Do I really have to explicitly create the buffer?

My suggestion is that both the versions should work.

**Comment by mikolalysenko** [comment]
Yeah, this is a bug.  I'll take a shot at fixing it.
