### ISSUE TITLE
The batch example is unbearable to look at.

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#18]
In the batch example
http://regl.party/examples?batch

there are some triangles in the background that flashes so fast it is probably epilepsy inducing. It is impossible to read the code of that example, because you keep getting distracted by those accursed triangles.

I propose that you change the frequency that the triangles change their colors at. 

if you modify this code

```javascript
      Math.sin((0.1 + Math.sin(batchId)) * count + 3.0 * batchId),
      Math.cos(0.02 * count + 0.1 * batchId),
      Math.sin((0.3 + Math.cos(2.0 * batchId)) * count + 0.8 * batchId),
```
 
so that it becomes 

```javascript
    Math.sin( ((0.1 + Math.sin(batchId)) * count + 3.0 * batchId)*0.02 ),
      Math.cos( (0.02 * count + 0.1 * batchId)*0.02 ),
      Math.sin( ((0.3 + Math.cos(2.0 * batchId)) * count + 0.8 *batchId )*0.02 ),
```

the example is suddenly much more bearable to look at. 

The dynamic demo suffers from the same problem:
http://regl.party/examples?dynamic
Also the lighting demo flashes at an ridiculous rate
http://regl.party/examples?lighting

So I would suggest that you do the same thing with them.

What do you think?

**Comment by mikolalysenko** [comment]
Sounds great!

**Comment by Erkaman** [comment]
So shall I make a pull request with the fixes?

**Comment by mikolalysenko** [comment]
Go for it!
