### ISSUE TITLE
Why is the parameter 'zpass' named 'pass'?

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#180]
When specifying a stencil operator:

```
opFront: {
      fail: 'keep',
      zfail: 'keep',
      pass: 'keep'
    }
```

'pass' is used to denote the parameter 'zpass' of the WebGL function [gl.stencilOp](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilOpSeparate).

Can I ask why you renamed 'zpass' to 'pass'? I think renaming a WebGL parameter like that will just cause confusion among some users. I think it may trip up people going from WebGL to regl.

**Comment by Erkaman** [comment]
And if you really want to rename it, then you should prevent people from using the parameter 'zpass'. So that if you accidentally use 'zpass', spit out an error message that explains that 'zpass' has been renamed 'pass'.

**Comment by mikolalysenko** [comment]
We should probably check the properties of all arguments to state variables.  This would go a long way to catching typos and other mistakes.

**Comment by msfeldstein** [comment]
The documentation on the website still shows 'pass' (and silently fails, it should probably throw an error
