### ISSUE TITLE
The README should list projects using regl. 

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#181]
In addition to providing a gallery of examples, I think it would be good if we provided a list of awesome projects using regl. Some projects we could add to this list are:

* https://github.com/Erkaman/wireframe-world
* https://github.com/realazthat/glsl-sat
* https://github.com/rreusser/regl-smooth-life
* http://fivethirtyeight.com/features/gun-deaths/
* https://github.com/dfcreative/gl-fourier

If anyone knows any more projects, please add them here!

**Comment by mikolalysenko** [comment]
Also a note here:  We should add an invitation so that people can submit PRs with their own projects.
