### ISSUE TITLE
Should be able to specify both stencil ops through 'op'

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#182]
Right now, we can specify stencil ops for front and back separately:

```
opFront: {
      fail: 'keep',
      zfail: 'keep',
      pass: 'keep'
    },
    opBack: {
      fail: 'keep',
      zfail: 'keep',
      pass: 'keep'
    }
```

But it would sometimes be convenient if we could set them both to the same value, through a property named 'op'

**Comment by Erkaman** [comment]
I will solve this issue.

**Comment by Erkaman** [comment]
Lol. This was harder than I expected. Someone else will have to do this.

**Comment by mikolalysenko** [comment]
Working on it
