### ISSUE TITLE
Can we show the source command for all error messages?

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#216]
Consider the below program:

```javascript
const regl = require('../regl')()

regl( {
  frag: [
    'precision mediump float;',
    'uniform vec4 color;',
    'void main() {',
    '  gl_FragColor = vec4(1, 0, 0, 1);',
    '}'
  ].join('\n'),

  vert: [
    'precision mediump float;',
    'attribute vec2 position;',
    'void main() {',
    '  gl_Position = vec4(position, 0, 1);',
    '}'
  ].join('\n'),

  attributes: {
    position: regl.buffer([
      [0, 0],
      [1, 0],
      [1, 1],
      [0, 1],
      [1, 0],
      [1, 1]
    ])
  },

  count: 6,
  blend:{
    equation: {
      rgb: 'reverse subtract',
      alpha: 'add'
    },
  },
  stencil: {
    enable: true,
    mask: 0xff,
  }
})()
```

If we comment out the fragment shader, we get a very useful error message

```
check.js:21Error: (regl) missing fragment shader in command http://130.241.189.159:9966/bug2.js:4:1 
called from http://130.241.189.159:9966/bug2.js:43:3(…)
```

this useful error message shows you the exact command that causes the issue. However, if you for instance set

```javascript
      alpha: 'adddddd'
```

in the above program, you don't get a very good error message

```
check.js:21Error: (regl) unknown parameter (addddd): blend.equation.alpha. 
possible values: add,subtract,reverse subtract in command unknown(…)
```

this error message is bad, because it doesn't show you the source command. You also get that kind of error message if you set

```
    mask: 'bla',

```

for the stencil buffer.

So my question: is it possible to implement so that we always get to know the source command for all error messages? For some error messages we get to know the source command, but it is far from all. But knowing the source command could be very useful when debugging big code bases.

 This would make regl more pleasant to use, I think.

**Comment by mikolalysenko** [comment]
Yep, that is a bug with the error checking in blend mode.  It should report that information.

**Comment by Erkaman** [comment]
actually it seems like it doesnt work for static in general. for dynamic it seems to work
