### ISSUE TITLE
Examples from `regl.party` do not work for me

### ISSUE THREAD

**Issue by serapath** [mikolalysenko/regl#217]
```
mkdir example3d
cd example3d
npm init # go with all defaults
atom index.js # copy & paste regl.party/exapmples content, save & close
npm install regl gl-mat4 bunny --save # or whatever `require(...)`ed
echo "<body><script src="bundle.js"></script></bundle>" > index.html
npm install browserify-livereload watchify --save-dev
# add to `package.json` `..."scripts": {}...` section and save file
"start": "watchify index.js -p [ browserify-livereload --host 127.0.0.1 --port 1337 ] -o bundle.js -dv",
# start
npm start
# open "index.html" in browser
```

Only the `basics` and `elements` example works. The others only show a black screen and don't throw any error message.
What can i do?

**Comment by mikolalysenko** [comment]
This is probably a bug in the regl.party website which is hosted on a separate repo:

https://github.com/freeman-lab/regl-site

**Comment by freeman-lab** [comment]
@serapath to clarify, are you saying that the examples don't render on the `regl.party` site, or that when you copy the content and then run locally with `regl` it doesn't work? It sounds like it might be the second thing, and if so, that's probably because the examples on the site need to be updated to the latest `regl` release, will do that today.

**Comment by serapath** [comment]
no, they don't render locally after `npm install` and copy pasting the code samples from the website.
What i did is:
```bash
mkdir example3d
cd example3d
npm init
atom index.js # copy & paste regl.party/exapmples content, save & close
npm install regl --save # and other dependencies used by the copied example
echo "<body><script src="bundle.js"></script></bundle>" > index.html
npm install browserify-livereload watchify --save-dev
# add to `package.json` `..."scripts": {}...` section and save file
"start": "watchify index.js -p [ browserify-livereload --host 127.0.0.1 --port 1337 ] -o bundle.js -dv",
npm start
# open "index.html" in browser
```

**Comment by Erkaman** [comment]
But can you run them in budo? Go to the `example/` folder, and trying running some examples. run like this

```sh
budo --live --open basic.js
```

**Comment by Erkaman** [comment]
Also, have you tried out the examples in the [gallery](https://mikolalysenko.github.io/regl/www/gallery.html)?

**Comment by Erkaman** [comment]
The OP hasn't responded in like 7 days, so maybe we should just close due to inactivity?

**Comment by mikolalysenko** [comment]
Yeah I think so.  We should probably link the issues related to setting up and using budo more prominently.

**Comment by freeman-lab** [comment]
For reference, I think this might have been because the examples were out of date relative to the installed version of regl, just fixed that.
