### ISSUE TITLE
The Gallery needs a tagging system.

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#228]
The gallery has become slightly big, and I think this makes it hard to navigate for beginners. As I see it, we have three kinds of examples:

* Basic examples. Such as, `basic.js` and `batch.js`
* Advanced examples. Such as `deferred_shading.js` and `shadow-volume.js`
* GPGPU examples. Such as `reduction.js` and `graph.js`

If we could add some kind of tagging system to the gallery, it would be much easier for beginners to find basic examples. And people who are more advanced will have an easier time finding advanced examples.

**Comment by freeman-lab** [comment]
Totally agree with this, was thinking about the same for the live versions on `regl.party` as well. Should we embed tags in file names? Or a commented out first line of each file? Something else?

**Comment by Erkaman** [comment]
In the beginning of every example, we already have a multi-line description comment that is extracted and used in the gallery. 
We can probably just put the tags in the very beginning of that comment.

**Comment by freeman-lab** [comment]
Ah right, that sounds good to me!

**Comment by Erkaman** [comment]
I will throw together a simple tagging system.
You will be able to filter out tags in the gallery with a simple dropdown menu.
We can possibly do more advanced filtering in the future.

**Comment by Erkaman** [comment]
Fixed in PR #283.
