### ISSUE TITLE
subdata doesn't seem to handle an array of typed arrays.

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#23]
The method `subdata` does not seem to handle arrays of typed arrays. If I pass subdata() an array of the form `[[Float32Array[3], Float32Array[3], Float32Array[3],...]`, nothing gets rendered at all. See the below minimal example:

```javascript
const canvas = document.body.appendChild(document.createElement('canvas'))
const fit = require('canvas-fit')
const regl = require('../regl')(canvas)
const mat4 = require('gl-mat4')
const camera = require('canvas-orbit-camera')(canvas)
window.addEventListener('resize', fit(canvas), false)
const vec3 = require('gl-vec3')

// configure intial camera view.
camera.rotate([0.0, 0.0], [0.0, -0.4])
camera.zoom(-10.0)

// geometry arrays.
const elements = []
var position = []

const N = 10 // num quads of the plane
// create plane vertices
var row
var col
for (row = 0; row <= N; ++row) {
  var z = (row / N) * (8) + -4
  for (col = 0; col <= N; ++col) {
    var x = (col / N) * (8) + -4

    // THE IMPORTANT PART IS BELOW
    //
   //
   //

    // this works!
    position.push(  [x, 0.0, z]  );   

    // but this doesn't work
    //    position.push( vec3.fromValues(x, 0.0, z));

  }
}

const positionBuffer = regl.buffer({
  length: position.length * 3 * 4,
  type: 'float',
  usage: 'dynamic'
})

// create plane faces.
for (row = 0; row <= (N - 1); ++row) {
  for (col = 0; col <= (N - 1); ++col) {
    var i = row * (N + 1) + col

    var i0 = i + 0
    var i1 = i + 1
    var i2 = i + (N + 1) + 0
    var i3 = i + (N + 1) + 1

    elements.push([i3, i1, i0])
    elements.push([i0, i2, i3])
  }
}

const drawPlane = regl({
  context: {
    view: () => camera.view()
  },
  frag: `
  precision mediump float;
  varying vec3 vPosition;
  void main () {
    gl_FragColor = vec4(vPosition.xyz, 1.0);
  }`,

  vert: `
  precision mediump float;

  attribute vec3 position;
  uniform mat4 projection, view;
  varying vec3 vPosition;
  void main() {
    vPosition = position;
    gl_Position = projection * view * vec4(position, 1);
  }`,

  uniforms: {
    view: regl.context('view'),
    projection: ({viewportWidth, viewportHeight}) =>
      mat4.perspective([],
                       Math.PI / 4,
                       viewportWidth / viewportHeight,
                       0.01,
                       1000)
  },
  attributes: {
    position: {
      buffer: positionBuffer,
      normalized: true
    },
  },
  elements: regl.prop('elements')
})

regl.frame(({deltaTime}) => {
  regl.clear({
    color: [0, 0, 0, 255],
    depth: 1
  })
  positionBuffer.subdata(position)
  drawPlane({elements})
  camera.tick()
})
```

Now notice that if I push normal arrays to `position` like this:

```
    position.push(  [x, 0.0, z]  );
```

then it works, and I am able to render a plane

<img width="496" alt="screen shot 2016-07-01 at 09 34 32" src="https://cloud.githubusercontent.com/assets/602313/16514906/133e5c48-3f6f-11e6-8602-3fb145797bdb.png">

But if I change that line to

```
    //    position.push( vec3.fromValues(x, 0.0, z));
```

I just get a black screen. And that is because `gl-vec3` creates the vectors as `Float32Array[3]`. 
And it would be very nice if I could pass an array of the form `[[Float32Array[3], Float32Array[3], Float32Array[3],...]` to `subdata`, because then I could use the methods from `gl-vec3` directly on the vertices in the array `position`.  

But note that you can mostly work around this issue. You can actually just store the vectors as normal arrays `[]` in `position`, and then use the functions from `gl-vec3` on those arrays. However, you have to be careful, because you can't use `fromValues `, `clone`, `create`, or `clone`, because these all return a typed array `Float32Array[3]`. So if you want to clone a vector, you'll have to do

```
var clonedVector = [v[0], v[1], v[2]]
```

which is a bit annoying. So it would be great if you could pass an array `[[Float32Array[3], Float32Array[3], Float32Array[3],...]` to `subdata`. It may also be that the other buffer methods also don't handle this special case. 

And it may be that you don't support this by design? If that is the case, you should probably explicitly write that in the documentation...

**Comment by mikolalysenko** [comment]
This behavior is a bug.  Basically there are a bunch of places where the code is checking if the input is an Array using `Array.isArray` and this ends up being too restrictive.
