### ISSUE TITLE
rgb/float combination for texture creation produces rgba texture.

### ISSUE THREAD

**Issue by realazthat** [mikolalysenko/regl#239]
(Checked against public version `0.11.0`).

See [requirebin](http://requirebin.com/?gist=c3b9e820e36d7890ef353b436d1c39d6).

Key excerpts:

```

    let fbo = regl.framebuffer({
      color: regl.texture({
        color: 'rgb',
        type: 'float'
      }),
      depth: false,
      stencil: false
    });

    console.log('texture.internalFormat:',fbo.color[0]._texture.internalformat);
    console.log('texture.type:',fbo.color[0]._texture.type);
```

Output:

```
texture.internalFormat: 6408
texture.type: 5126
```

Constants show that `6408=0x1908=rgba`, and not the expected `rgb`.

**Comment by Erkaman** [comment]
The problem is that using rgb rendertargets should not be allowed, so it should be throwing an exception. But it is not doing that for some reason.

**Comment by realazthat** [comment]
@Erkaman what happens if the texture is created without the FBO?

**Comment by Erkaman** [comment]
rgb textures are allowed, if that's what you are asking. But rgb fbos are not allowed.

**Comment by mikolalysenko** [comment]
Are rgb fbos allowed or not?  Some browsers seem ok with it.

At any rate this is not really a 1.0 blocker so I'm taking the milestone tag off.

**Comment by Erkaman** [comment]
rgb fbos is not standard. See
https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.6

only when using rgba, we have a guarantee that it will work.

**Comment by Erkaman** [comment]
working on this right now.

**Comment by Erkaman** [comment]
Turns out that the code posted in the issue was wrong. It should have been

```javascript
   let fbo = regl.framebuffer({
      color: regl.texture({
        format: 'rgb', // CHANGE IS HERE
        type: 'float'
      }),
      depth: false,
      stencil: false
    });
```

for this code, it correctly reports that the color attachment is invalid. Which is expected behaviour. 

Close.
