### ISSUE TITLE
Batch render instanced commands

### ISSUE THREAD

**Issue by jpweeks** [mikolalysenko/regl#264]
Maybe this is a weird use case, but commands that use instancing throw an error if they're rendered in a batch.

Test case: https://jsbin.com/robisa/1/edit?js,console,output

**Comment by Erkaman** [comment]
hmm, it works for me if I run it in `budo`, though. Maybe the standalone library is broken. Can you trying running in `budo` as well?

**Comment by jpweeks** [comment]
Yeah, I first encountered it when working on a prototype run with `budo`.

**Comment by Erkaman** [comment]
Hmm, I'll look into this tomorrow some.

**Comment by Erkaman** [comment]
Yeah, I've been able to reproduce it now. I will see if I can fix it.

**Comment by Erkaman** [comment]
With PR #267 the problem should be solved.
