### ISSUE TITLE
Examples at http://regl.party/examples do not work

### ISSUE THREAD

**Issue by r03ert0** [mikolalysenko/regl#269]
error in the web console:

wzrd.in/multi:1 GET https://wzrd.in/multi 404 (Not Found)
VM4420:1 Uncaught SyntaxError: Unexpected token C

(chrome on os x 10.11.15)

**Comment by Erkaman** [comment]
Do the examples in the gallery work for you?
https://mikolalysenko.github.io/regl/www/gallery.html

**Comment by freeman-lab** [comment]
Weird, yeah worth checking that, they both currently work for me in Chrome on OS X 10.11.

Soon we'll be putting both the gallery and live editor on the `regl.party` site, so it'll be easier to get to the static version if the editor isn't working.

**Comment by r03ert0** [comment]
hmmm... now everything works...
i'll close the issue

**Comment by Erkaman** [comment]
lol everything just works suddenly :D
