### ISSUE TITLE
Default texture wrapS and wrapT in documentation. 

### ISSUE THREAD

**Issue by ataber** [mikolalysenko/regl#285]
On [this line](https://github.com/mikolalysenko/regl/blame/gh-pages/API.md#L1658) of the documentation, it says the default value for wrapS and wrapT is `repeat`, but on [this line](https://github.com/mikolalysenko/regl/blob/gh-pages/lib/texture.js#L1008) it looks like the default value is `clamp`. My own experience backs this up, as my textures were not being repeated by default.

**Comment by mikolalysenko** [comment]
Yep, that looks like a bug.
