### ISSUE TITLE
Question: How to  do dynamic vertices?

### ISSUE THREAD

**Issue by micha149** [mikolalysenko/regl#292]
Hey!

I just played a bit around and really like the functional way which regl gives to me. My project structure is a little bit more complicated, but I try to explain the core of my problem.

I have a component class which creates a regl draw function when it gets instanciated. For optimization reasons I do this only once per class/gl-context combination. This draw function will be used to draw all instances of this class via the batch rendering method. It is possible to pass some properties to the component which may affect the vertices I need to render. For example, the `Cube` class: It uses [geo-3d-box][1] to create the vertices and you can pass a size and the number of subdivisions. So the vertices differ from instance to instance.

I just tried to use a prop for my positions, but I didn't know what to do with `count`:
```
regl({
    attributes: {
        positions: regl.prop('vertices')
    },
    count: // ????
});
```

I found also that this `elements` thing sounds promising but I did not understand how it plays together with the vertices I need.

Can someone tell me how this has to be done? Thanks!

[1]: https://www.npmjs.com/package/geo-3d-box "geo-3d-box on npmjs.com"

**Comment by Erkaman** [comment]
Ok, let me explain how `count` and `elements` work.

To draw a fullscreen quad using `count`, do this:

```javascript
const regl = require('../regl')()

regl({

  // In a draw call, we can pass the shader source code to regl
  frag: `
  precision mediump float;
  uniform vec4 color;
  void main () {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
  }`,

  vert: `
  precision mediump float;
  attribute vec2 position;
  void main () {
    gl_Position = vec4(position, 0, 1);
  }`,

  attributes: {
    position: [
      [-1, -1],
      [1, -1],
      [1, 1],

      [-1, -1],
      [1, 1],
      [-1, 1],
    ]
  },

  count: 6
})()
```

`count: 6` specifies that we use the six vertices of the
attribute `position` to render. And since the default primitive is
`triangles`, we end up rendering `6 / 3 = 2` triangles. So we get a quad.

Now let us do the same thing with `elements`:

```javascript
const regl = require('../regl')()

regl({

  // In a draw call, we can pass the shader source code to regl
  frag: `
  precision mediump float;
  uniform vec4 color;
  void main () {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
  }`,

  vert: `
  precision mediump float;
  attribute vec2 position;
  void main () {
    gl_Position = vec4(position, 0, 1);
  }`,

  attributes: {
    position: [
      [-1, -1],
      [1, -1],
      [1, 1],
      [-1, 1],
    ]
  },

  elements: [ [0, 1, 2], [0, 2, 3] ]
})()
```

the interesting part here is `elements: [ [0, 1, 2], [0, 2, 3] ]`. It
means this: We draw two triangles(since, again, the default primitive is `triangles`). The first triangle uses the
vertices with indices `0,1,2` from `position`. And the second one uses
the vertices with indices `0,2,3`. As can be seen, `elements` allow us
to reuse vertices, so it is more space efficient. But we are drawing the exact same two triangles as in the first example.

Do you understand `count` and `elements` now? You can also read the
[docs](https://github.com/mikolalysenko/regl/blob/gh-pages/API.md#drawing)
about this.

**Comment by Erkaman** [comment]
You are also welcome to the [chat](https://gitter.im/mikolalysenko/regl) if you want to discuss things with us, and just want help.

**Comment by micha149** [comment]
Thanks for your explanation. I got it. Because `geo-3d-box` returns an object with `cells` and `position` I think the elements ways is the right one. The following code works…

```javascript
export class Cube extends Component {

    static defaultProps = {
        subdivisions: 1,
        wireframe: false,
        color: [1, 0, 0, 1]
    }

    initDrawCommand(regl) {
        return regl({
            frag: `
                precision mediump float;
                uniform vec4 color;
                void main() {
                    gl_FragColor = color;
            }`,

            vert: `
                uniform float foo;
                precision mediump float;
                attribute vec3 position;
                void main() {
                    gl_Position = vec4(position, 1);
            }`,

            attributes: {
                position: regl.prop('positions'),
            },

            uniforms: {
                color: regl.prop('color'),
            },

            elements: regl.prop('cells')
        });
    }

    componentDidMount() {
        const {positions, cells} = createBox({ size: this.props.subdivisions, segments: this.props.subdivisions });
        const data = this.node.data;
        data.color = this.props.color;
        data.positions = positions;
        data.cells = cells;
    }
}
```

Or is it better to initialize a elements buffer using `regl.elements()` and update it with the returned function?

**Comment by Erkaman** [comment]
If you need to have a very dynamic mesh, and need to often modify the vertices and elements(like, update the mesh every single frame), you should use `regl.elements()`. Otherwise, don't use it. The way you are doing it now is much more convenient.

**Comment by micha149** [comment]
OK, thank you very much!
