### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [mikolalysenko/regl#295]
Hello @mikolalysenko ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I think the main file is `dist/regl.js` and `dist/min.js`.
Is necessary to add `dilst/regl.unchecked.js` and some dependencies under `lib/`?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8812

**Comment by Erkaman** [comment]
Yes, 

* dist/regl.js is the version that does sanity checking, and outputs error messages.
*  and dist/min.js is the optimized and minified version that strips away all that. 

and you should host both of them.
And they are completely standalone, so you shouldn't add any other dependencies. 

Although we just bumped a new minor version, and forgot to update those two files. I will try and update them later.

**Comment by kennynaoh** [comment]
Thanks!
And I think `dist/regl.unchecked.js` is not necessary, right?

**Comment by Erkaman** [comment]
Nope.

**Comment by kennynaoh** [comment]
Ｔhanks!

**Comment by Erkaman** [comment]
So I updated those two files now.

Well, if you got your question answered, then I will close the issue now.

**Comment by kennynaoh** [comment]
Thanks!

**Comment by kennynaoh** [comment]
Because there has no `dist/` in version `0.0.0` on [npm](https://www.npmjs.com/package/regl), what should I do?

**Comment by Erkaman** [comment]
I think you can just safely ignore that version `0.0.0 ` then. It's such an early version that it's probably not even usable for anything. I think.
