### ISSUE TITLE
Passing array straight to attributes

### ISSUE THREAD

**Issue by dfcreative** [mikolalysenko/regl#3]
Hi @mikolalysenko!

Currently we are forced to pass buffer instance to attributes:
```js
return regl({
	vert: `
	precision highp float;
	attribute vec2 position;
	void main() {
		gl_Position = vec4(position, 0, 1);
	}
	`,

	frag: `
	precision highp float;
	void main () {
		gl_FragColor = vec4(0,0,0, 1);
	}
	`,

	attributes: {
		position: regl.buffre([-1,-1, -1,3, 3,-1])
	},

	count: 3
});
```
Wouldn’t it be easier to be able to pass just an array to `attributes` property? Not a big trouble, but still a bit more easier to remember, especially for the users who are not into webgl terminology.

That is mentioned in [API](https://github.com/mikolalysenko/regl/blob/gh-pages/API.md#attributes), but the chunk with plain array instead of buffer does not render anything.

**Comment by mikolalysenko** [comment]
One problem with this proposal is that if you pass in an array to an attribute, then regl assumes that it is a constant attribute, as you would specify using using `gl.vertexAttrib4f(..)` for example.  If we allow for array inputs, then this case is hard to disambiguate.  

Also for dynamic attributes, then returning an array and converting it to a buffer each frame would cause serious performance problems. For example, you could write something like:

```javascript
const drawMesh = regl({
   vert: `
    precision highp float;
    attribute vec2 position;
    void main() {
        gl_Position = vec4(position, 0, 1);
    }
    `,

    frag: `
    precision highp float;
    void main () {
        gl_FragColor = vec4(0,0,0, 1);
    }
    `,

    attributes: {
        position: regl.prop('position')
    },

   count: regl.prop('count')
})
```

If the position attribute is an array, then we'd have to keep track of a buffer reference internally for the draw call and use that to stream out the returned values.

**Comment by mikolalysenko** [comment]
Still it is a pretty good idea, and something that would be nice to have if there is an unambiguous and efficient way to implement it.

**Comment by dfcreative** [comment]
Thanks for the explanation, totally makes sense.
As far it is not an issue, I close it then.
