### ISSUE TITLE
`life` example is broken

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#30]
The `life` example seems to have broken with the texture rewrite. If I run the example with `budo`, I get the error

```
check.js:21Error: (regl) invalid regl object for attachment(…)
```

the `life` demo in the gallery also does not work. It seems the issue is that you can't use `regl.texture` as an attachment to `regl.framebuffer`.

**Comment by mikolalysenko** [comment]
Solved in PR #31
