### ISSUE TITLE
About the default value of `count`

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#300]
The current default value of `count` is 0, but I propose that we should use a different value.

consider the below draw-call, which draws a red triangle

```javascript
regl({
  frag: `
  precision mediump float;
  void main () {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
  }`,

  vert: `
  precision mediump float;
  attribute vec2 position;
  void main () {
    gl_Position = vec4(position, 0, 1);
  }`,

  attributes: {
    position: [
      [-1, 0],
      [0, -1],
      [1, 1]
    ]
  },

  count: 3
})()
```

here I have to specify `count: 3`, since the default value of `count` is 0. But shouldn't the value `3` be obvious from the fact that the length of `position` is 3?

So I propose that if `elements` and `count` is not specified, then we should use `attributes` to figure out  `count`. What do you think?

**Comment by mikolalysenko** [comment]
It is really hard to make this work in general since the attributes can be unstructured buffers.  Also you can have multiple attributes with different sizes, and some can be dynamic, etc.  which all make this really hard to compute.  As a result it is just simpler to leave the count up to the user.

**Comment by Erkaman** [comment]
Hmm, yeah, I see what you mean. Yeah, implementing this is probably more trouble than it's worth. Let's not do that.

Closed.
