### ISSUE TITLE
"elements" example throws lineWidth error

### ISSUE THREAD

**Issue by letmaik** [mikolalysenko/regl#303]
```
Error: (regl) invalid line width, must positive number between 1 and 1 in command unknown
```
When I change the lineWidth from 3 to 1, it works.
Tested in latest Firefox and Chrome on Windows 7.

**Comment by Erkaman** [comment]
Well, that just means that we need to make sure we clamp the line-width down to the maximum value of lineWidth for the browser.

**Comment by Erkaman** [comment]
With PR #305 this issue should be solved. Can you check if it works now?

**Comment by letmaik** [comment]
That works, yes. Thanks!

**Comment by Erkaman** [comment]
Alright, issue solved then. 

Closed.

**Comment by ataber** [comment]
Just ran into this. What about having `regl` coerce `lineWidth` to be within the bounds, and then emitting a console warning? However, implicitly coercing user input can be slippery slope. Thoughts?

**Comment by kaosat-dev** [comment]
Also stumbled onto this after a Chrome update (which apparently removed anything except 1 for lineWidth , even on Mac).
Not sure coercing is a good idea although I get the appeal:  seems more 'user space'/dev concern to detect valid range and set values accordingly ? or provide a helper to do this?

**Comment by caesarsol** [comment]
@kaosat-dev same here. 
What I'm surprised about is that lineWidth >1 on Chrome/MacOS has always worked...

**Comment by fczuardi** [comment]
Should we reopen this? (lineWidth 2 didn't worked for me on Mac OSX 10.11.6 (el capitan) Chrome canary 60.0.3079.0 running with the chrome://flags/#ignore-gpu-blacklist because of my old machine.

**Comment by fczuardi** [comment]
oh, nevermind, this bug was about the example only :P

**Comment by pailhead** [comment]
greetings from 2022, this still doesn't work.
