### ISSUE TITLE
"texture" example broken on Firefox

### ISSUE THREAD

**Issue by letmaik** [mikolalysenko/regl#304]
In Chrome it works, but on Firefox (48.0.2) the console says:
```
uncaught exception: incorrect header check
```

**Comment by mikolalysenko** [comment]
Weird.  It might also be a bug in [resl](https://github.com/mikolalysenko/resl)?

**Comment by Erkaman** [comment]
Err, what's your operating system? And does the other `resl` examples work for you? Does for example the [video example](https://mikolalysenko.github.io/regl/www/gallery/video.js.html) work for you?(you should be seeing a video of a dog.)

**Comment by letmaik** [comment]
Strangely both work when I use the direct URLs like https://mikolalysenko.github.io/regl/www/gallery/texture.js.html. I can't actually test the video one inside the normal examples page as I can't scroll down on the right side and my screen doesn't show everything already.

**Comment by Erkaman** [comment]
Ah, you mean that it doesn't work on `regl.party`? Then that's something that @freeman-lab will have to take a look at, since he's the one that made that site.

**Comment by letmaik** [comment]
Yes exactly.

**Comment by freeman-lab** [comment]
thanks, i'll take a look!

**Comment by mikolalysenko** [comment]
Ok, this is a regl-site issue not a problem in regl.  Going to close.
