### ISSUE TITLE
`destroy` is never called for `elements`

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#40]
The `elements` buffers are never destroyed. There is a method

```
    reglElements.destroy = function () {
      stats.elementsCount--

      check(elements.buffer !== null, 'must not double destroy elements')
      buffer.destroy()
      elements.buffer = null
    }
```

in `lib/elements.js`, but it is never ever called. But it should probably be called somewhere, so that we can clean up after the `elements` buffers

**Comment by mikolalysenko** [comment]
Yeah, the reason for this is that element buffers don't have any resources other than their vertex buffer.  Still calling the destructor on the element buffers shouldn't hurt anything and it is probably useful here to implement the resource counting.
