### ISSUE TITLE
custom mipmap feature of `regl.texture` is undocumented

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#47]
If I have understood things correctly, if the option `mipmap` of `regl.texture()` is an array, 

https://github.com/mikolalysenko/regl/blob/gh-pages/lib/texture.js#L816

then you can use it to send in your own, custom mipmaps to the texture, without having to use the ones generated by OpenGL. But this feature does not seem to be documented anywhere in the API, but it should probably be.

**Comment by mikolalysenko** [comment]
Yeah.  For `mipmap` you can pass in one of the following:

* A boolean value, which if `true` tells WebGL to generate mipmaps
* A string which sets the `glHint` for mipmapping and also causes the texture to regenerate mipmaps
* An array of mipmap images

We should probably add this information to the API document.

**Comment by Erkaman** [comment]
As of PR #108 this issue is resolved.
