### ISSUE TITLE
Updating textures data

### ISSUE THREAD

**Issue by dfcreative** [mikolalysenko/regl#5]
Hi!

There is another concern I can’t resolve.
What is the designed way to update texture’s data?
The [test](https://github.com/mikolalysenko/regl/blob/gh-pages/test/texture.js) is not complete yet, and [docs](https://github.com/mikolalysenko/regl/blob/gh-pages/API.md#textures) do not cover that case yet.

Should I return texture instance each time in dynamic uniform, like that:
```js
uniforms: {
  image: function () {
    return regl.texture(src);
  }
}
```

Or I can save reference to created texture and modify it in some fashion?

Thanks!

**Comment by mikolalysenko** [comment]
All resources have the same path way for updating.  To update a texture, you do the following:

```javascript
// create texture
var myTexture = regl.texture('mytexture.png')

//  ... do stuff

// update texture
myTexture(someNewData)
```

This is still a work in progress though and I'm planning on adding some extra methods for updating subimages within a texture.

**Comment by dfcreative** [comment]
Sweet, thanks.
