### ISSUE TITLE
Some unused code in `lib/dynamic.js`

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#50]
I think that there may be some unused features in `lib/dynamic.js`

At this line here 
https://github.com/mikolalysenko/regl/blob/gh-pages/lib/dynamic.js#L9

`  this.id = (VARIABLE_COUNTER++)
`
you declare an id for the dynamic variable. But as far as I can see, it is never used anywhere.

Also here https://github.com/mikolalysenko/regl/blob/gh-pages/lib/dynamic.js#L58
```

  switch (typeof data) {
    case 'boolean':
    case 'number':
    case 'string':
      return new DynamicVariable(type, toAccessorString(data + ''))

    case 'undefined':
      return new DynamicVariable(type | DYN_PENDING_FLAG, null)

    default:
      check.raise('invalid property type')
  }
```

But in the way that we use `defineDynamic`, I think that `data` is always a string. Because it is the string in the shortcuts like `regl.prop('scale')`. So why do you handle the cases `boolean` and `number`? Also, does the `undefined` case ever occur? 

Also at https://github.com/mikolalysenko/regl/blob/gh-pages/lib/dynamic.js#L5

```
var DYN_FUNC = 0
var DYN_PENDING_FLAG = 128
```

and at https://github.com/mikolalysenko/regl/blob/gh-pages/regl.js#L30 we have

```
var DYN_PROP = 1
var DYN_CONTEXT = 2
var DYN_STATE = 3
```

shouldn't all these five be in one single place? Why are you splitting them up?

**Comment by Erkaman** [comment]
Also, there's some code duplication in `lib/core.js`. 
https://github.com/mikolalysenko/regl/blob/gh-pages/lib/core.js#L19
```
var DYN_FUNC = 0
var DYN_PROP = 1
var DYN_CONTEXT = 2
var DYN_STATE = 3
```

which is duplicated code of those constants I showed earlier
 https://github.com/mikolalysenko/regl/blob/gh-pages/regl.js#L30 

code duplication is very bad practice. Should maybe refactor these constants into a separate module.

**Comment by mikolalysenko** [comment]
Yeah, that's messy.  I can take a look at it once the FBO stuff is done, or if it bothers you enough feel free to take a shot at it sooner.

**Comment by Erkaman** [comment]
I can take a look at it if I have the time.
