### ISSUE TITLE
dynamic viewports and scissors do not allow negative x- and y-values

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#51]
In the viewport and scissors parsing of the code generator, for dynamic you do a check for negative x- and y-values
https://github.com/mikolalysenko/regl/blob/gh-pages/lib/core.js#L653

```
          check.optional(function () {
            env.assert(scope,
              BOX_X + '>=0&&' +
              BOX_Y + '>=0&&' +
              BOX_W + '>0&&' +
              BOX_H + '>0',
              'invalid ' + param)
          })
```

but you do not do the corresponding check for static. You only do this:

https://github.com/mikolalysenko/regl/blob/gh-pages/lib/core.js#L600
```
        var x = box.x | 0
        var y = box.y | 0
```

so you do not check for negative x- and y-values for static. This is weird and inconsistent, and should be looked over.

Also, you do not seem to have any test cases for viewports with negative x- and y-values. That's probably why the above bug slipped through.

**Comment by mikolalysenko** [comment]
Yeah, this stuff needs better testing.  I'm planning on rolling some of this in with the upcoming fbo tweaks since viewports and scissor boxes are FBO dependent features.

**Comment by vorg** [comment]
Why are we enforcing positive only x and y for viewports? Only width and height are required to be positive https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/viewport

**Comment by mikolalysenko** [comment]
It shouldn't do that any more.  With the latest version you can now have negative viewports.
