### ISSUE TITLE
Test cases and examples for instancing

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#69]
We don't have any test cases for instancing yet.  The feature is implemented and based on some early experiments it seems to work, but we need some unit tests to make sure that everything is sane and all the edge cases are covered.

**Comment by Erkaman** [comment]
And we also need to mention this feature in the README somewhere, since it is a big selling point of the framework.

**Comment by Erkaman** [comment]
I will work on this issue.

**Comment by Erkaman** [comment]
Examples have been implemented. And test cases have also been implemented for the primitives `triangle` and `line`. But we also need to write test cases for the remaining primitives, before we are done.

**Comment by mikolalysenko** [comment]
It probably isn't necessary to test all primitive types.  As long as we hit all the major execution pathways (draw, batch, scope, etc.)  and input modes (constant, props, context, this, ...) then it should be good.

**Comment by Erkaman** [comment]
So close then?

**Comment by mikolalysenko** [comment]
Yep.
