### ISSUE TITLE
Fix rounding issues in viewport rendering

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#79]
We should force all examples to use a power-of-2 sized viewport and to implement correct rounding.  The current set up using 5x5 viewports is fragile and fails on some computers.  The following formula is correct and works whenever the shape of the viewport is 2^n -by- 2^n:

```glsl
vec4 pixelToClip(vec2 pixel, vec2 shape){
   return vec4(2.0 * (pixel + 0.5) / shape - 1.0, 0, 1)
}
```

**Comment by Erkaman** [comment]
Using a power-of-2 sized viewport does not always solve the issue, I found...

**Comment by mikolalysenko** [comment]
One solution would be to standardize everything on a fixed 8x8 viewport, which seemed to work ok on all systems tested.

**Comment by Erkaman** [comment]
Wait, did it really work on all systems? I don't remember...

**Comment by mikolalysenko** [comment]
I'm just going to write a unit test for it.  PR incoming...
