### ISSUE TITLE
Context loss

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#8]
Currently there is some preliminary infrastructure for handling context loss, but it isn't well tested yet and probably doesn't work.

In order to handle context loss events, regl should mirror the state of textures and buffers so that when the context is restored after a loss the state can be updated.  However doing this does increase the overhead of each buffer object so it should be something that users can opt-out of if they do not need this feature.

There should also be some event hook on context loss and restore so that users can implement their own policies for restoring GPU resident resources like framebuffer objects.

**Comment by mikolalysenko** [comment]
Here is an outline for how this policy could work:

* In the event of a context loss, the current RAF is cancelled and regl enters a suspended state until context is restored.
* Once context is restored all commands and static vertex attributes/elements are reinitialized.  
* Resources like buffers and textures are restored but their data is reset to 0.
* After all commands and resources have reinitialized then an event is fired which the user can trap via some API.

In this way we don't have to worry about complex mirroring logic.  All of these tradeoffs can be implemented with 0 overhead.

**Comment by Erkaman** [comment]
Wait, is this issue really resolved? As far as I can see, your test cases are not testing the recovery of static resources, and stuff.
