### ISSUE TITLE
Links to API docs are borked on www.npmjs.com

### ISSUE THREAD

**Issue by realazthat** [mikolalysenko/regl#82]
Links to the API docs on [npmjs.com](https://www.npmjs.com/package/regl) point to urls such as `https://github.com/mikolalysenko/regl/blob/master/API.md#textures` which results in 404s. Actual URLs should be of the form `https://github.com/mikolalysenko/regl/blob/gh-pages/API.md#textures`.

**Comment by mikolalysenko** [comment]
Thanks, I need to remember to rerun mdtoc before publishing the next version.
