### ISSUE TITLE
More examples!

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#9]
regl is starting to get to a somewhat stable point where we can begin building examples with it.  Having more examples is crucial for vetting the API and ferreting out edge cases/bugs that might be lurking in the API.

Anyone can submit an example as a pull request, and to do so all that is required is to fork this repo and then add the necessary file into the examples/ folder.

**Comment by Erkaman** [comment]
I will try implementing some slightly more advanced examples and see if I can uncover some bugs. Next, I will implement a simple cloth simulation, I think. That will allow us to see how will regl handles highly dynamic meshes.

**Comment by mikolalysenko** [comment]
Cool.  I'm currently working on some changes to the texture API that will make uploading data faster.  If you are going to be streaming data into a buffer you should use the new `buffer.subdata()` method to do the in place updates.

**Comment by Erkaman** [comment]
ok, thanks for the tip!

**Comment by Erkaman** [comment]
As of now, examples are provided for a majority of features. Some remaining features that need examples are:

* Instancing, as mentioned in issue #69 
* How to share code between shaders(like functions)

Once cubic framebuffers are implemented, we will need examples for these as well. Some possible examples are things like shadow mapping for point lights, and dynamic environment maps(e.g., for water reflections.)

**Comment by Erkaman** [comment]
Instance examples were implemented in PR #78.

Some more things that needs examples:

* Anisotropic filtering.

**Comment by mikolalysenko** [comment]
This issue is kind of vague/open ended.  We should split this into more specific/actionable examples and close it.

**Comment by Erkaman** [comment]
I split this issue into two separate issues #163 and #164. If you can come up with more examples that we need, create a separate issue for it.
