### ISSUE TITLE
We need to call `generateMipmap` in `texture.resize`

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#90]
If a texture uses a mipmap, and we resize it through `texture.resize`, then the old mipmap will become invalid. I think. So we need to regenerate it by calling `gl.generateMipmap` again, which we are currently *not* doing in `texture.resize`.  Otherwise, the resized texture will be using the old mipmap, which is weird.

**Comment by mikolalysenko** [comment]
Resizing a texture zeros out the texture, so it should probably zero all mip data as well.  No need to regenerate them if they're just 0.

That said we should initialize them to something if the texture had mipdata before it was resized.

**Comment by mikolalysenko** [comment]
Fixed in #144
