### ISSUE TITLE
Investigate floating point read pixels

### ISSUE THREAD

**Issue by mikolalysenko** [mikolalysenko/regl#97]
According to the spec, if either the extension [EXT_color_buffer_float](https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_float/) or [EXT_color_buffer_half_float](https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_half_float/) is enabled, then it is possible to call `gl.readPixels` with floating point input.

I've not confirmed this or verified that it works yet, but if true then this we should modify `regl.read()` to support this behavior.

**Comment by Erkaman** [comment]
I will take care of this.

**Comment by Erkaman** [comment]
But neither of those extensions are supported for me. They aren't supported on my Macbook running Intel integrated graphics, and neither on my stationary desktop running GTX960. Do you have it? Check here:
http://webglreport.com/

**Comment by mikolalysenko** [comment]
Nope, which is why I haven't implemented it yet.

**Comment by Erkaman** [comment]
well, then it is very hard to implement right now...

**Comment by Erkaman** [comment]
lol, Firefox implement  WEBGL_color_buffer_float , but not chrome! also the half-float one!

**Comment by Erkaman** [comment]
Like I said in the chat, due to spotty browser support, I am afraid we'll have to give up on using `regl.read` to read from floating point renderbuffers. However, we are able to use `regl.read` for floating point textures.

**Comment by Erkaman** [comment]
Due to spotty browser support, we decided on postponing this feature for now.
